### ISSUE TITLE
RecyclerView Adapter Issue

### ISSUE THREAD

**Issue by vsahu1986** [carlonzo/StikkyHeader#36]
When we update , add ,delete an item from Adapter , or Attach a new Adapter to RecyclerView when in Sticky mode , lots of White Space appear between sticky header and Recycler View

it is just because of Translation Y

**Comment by vipinhelloindia** [comment]
+1 

I tried adding 

 ViewHelper.setTranslationY(mRecyclerView,ViewHelper.getTranslationY(headerView));

Once adapter is updated , 
but the RecyclerView height wraped

**Comment by carlonzo** [comment]
yeah. I am aware of this problem. I need to find a solution.

**Comment by vsahu1986** [comment]
Any Tricky Solution You Suggest as of now .

**Comment by carlonzo** [comment]
I dont know. them problem is that the translation is not adjusted after an update. what you should do (and what I have to do) is to update it based on the top position of the first element.

**Comment by vsahu1986** [comment]
Sure will try

**Comment by vsahu1986** [comment]
Hey Carlonzo , When you gonna write a work around on it .

**Comment by carlonzo** [comment]
this weekend I started working on it.

**Comment by vsahu1986** [comment]
try registering content observer , so that any change can be reflection in appropriate translation ..

**Comment by carlonzo** [comment]
I've applied some fixes to the recyclerView here https://github.com/carlonzo/StikkyHeader/pull/40 but it still have problems when the dataSet changes.

**Comment by vipinhelloindia** [comment]
ok I will try and let you now ..

**Comment by carlonzo** [comment]
just an update: I've a solution for that. the problem appears because the scroll of the header has not adjusted after that the dataset has changed. applying the correct scroll in the preDraw, the problem is solved, but the animation is broken. I will work on that.

**Comment by vipinhelloindia** [comment]
great , thats why I requested you to add data set observer to detected changes .

**Comment by vipinhelloindia** [comment]
one more thing 
the data set can be completed changes , 

<b>From</b>

 public class ViewHolder extends RecyclerView.ViewHolder {

            private TextView text;

            public ViewHolder(View itemView) {
                super(itemView);
                text = (TextView) itemView.findViewById(android.R.id.text1);

                itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        final int position = getAdapterPosition();
                        mElements.add(position, "row " + position + " +");
                        notifyItemInserted(position);
                    }
                });

                itemView.setOnLongClickListener(new View.OnLongClickListener() {
                    @Override
                    public boolean onLongClick(View v) {
                        final int position = getAdapterPosition();
                        mElements.remove(position);
                        notifyItemRemoved(position);
                        return false;
                    }
                });
            }
        }
    }

**Comment by rehacktive** [comment]
got the same problem, it happens less without animation, but it still happens.
any workaround is welcome.

**Comment by vipinhelloindia** [comment]
@ Carlonzo; I added two case and also gone through #45 
You need to save the header scroll position and translated pixel . In some case the adapter count may go to zero , then how can we scroll back the header , as the scroll amount for RecyclerView is zero .

**Comment by carlonzo** [comment]
@vipinhelloindia the problem you are talking about has been resolved here https://github.com/carlonzo/StikkyHeader/commit/7e91e332ff713df7c6bfe47bb924748891d16ef9

a new version of StikkyHeader need to be released on maven.

**Comment by vipinhelloindia** [comment]
oh great I will check soon then , Thanks a lot @carlonzo

**Comment by hopesenddreams** [comment]
It's still broken in 0.0.3, I imported with:
url "https://oss.sonatype.org/content/repositories/snapshots/"
'com.github.carlonzo.stikkyheader:core:0.0.3-SNAPSHOT'

**Comment by sawcioo** [comment]
@carlonzo Could you release to maven?

**Comment by abdelrahmanhesham13** [comment]
Is there any solution for that ?!

**Comment by MiloshZelembaba** [comment]
yeah i'm currently having issues with this bug, an update would be appreciated!

**Comment by abdelrahmanhesham13** [comment]
@carlonzo Please update it
